config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :menbers 
  has_many :users, through: :menbers
  has_many :messages 
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.body?
       last_message.body
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/menber.rb
class Menber < ApplicationRecord
  belongs_to :group
  belongs_to :user




end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :body, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :menbers 
  has_many :groups, through: :menbers
  has_many :messages

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:id])
    @messages = @group.messages.includes(:user).where("id > ? ",params[:last_id])

  end
end

 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end


  def new
    @group = Group.new
    @group.users << current_user 
  end

  def create 
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else 
      render :new 
    end
  end

  

  def edit
  end

  def update 
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params 
    params.require(:group).permit(:name,{ :user_ids => []})
  end

  def set_group
    @group = Group.find(params[:id])
  end
  








end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create 
    @message = @group.messages.new(message_params)
    if @message.save 
      respond_to do |format|
        format.html { redirect_to "group_messages_path(params[:group_id])" }
        format.json
      end
    else  
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end 
  end

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end


  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def index

  @users = User.where('name LIKE(?)', "#{params[:keyword]}%").where.not(id: current_user)
  respond_to do |format|
    format.html
    format.json
  end
 end

 def edit 
 end

 def update 
   if current_user.update(user_params)
     redirect_to root_path
   else 
     render :edit
   end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      .chat-group-users
        - group.users.each do |member|
          #chat-group-user.chat-group-user.clearfix 
            %input{name: "group[user_ids][]", type: "hidden", value: member.id}
            %p.chat-group-user__name 
              = member.name
            - if current_user != member
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 
                削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/_side-chat.html.haml
.side-chat__left
  .left-chat__user-name
    = current_user.name
  %ul
    %li.edit
      = link_to new_group_path do
        =fa_icon 'edit', class: 'fas'
    %li.cog
      = link_to edit_user_path(current_user) do
        =fa_icon 'cog', class: 'fas'
.groups
  - current_user.groups.each do |group|
    = link_to group_messages_path(group) do
      .group
        .group__name
          = group.name
        .group__message
          = group.show_last_message
      

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  .side-chat
    = render "side-chat"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_flash-mob.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash-mob'
    = yield

app/views/layouts/new.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Create Account
      %h5 新規アカウントの作成
      = render "devise/shared/links"
    .account-page__inner--right.user-form
      = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
        = devise_error_messages!
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :password
            %i (英数字8文字以上)
          .field-input
            = f.password_field :password, autocomplete: "off"
        .field
          .field-label
            = f.label :password_confirmation
          .field-input
            = f.password_field :password_confirmation, autocomplete: "off"
        .actions
          = f.submit "Create Account", class: 'btn'

app/views/messages/_main-chat.html.haml
.main-chat__header{"data-group-id": "#{@group.id}"}
  .main-chat__header__box
    .main-chat__header__name
      = @group.name
    .main-chat__header__member
      Member :
      - @group.users.each do |member|
        = member.name
  .main-chat__header__edit
    = link_to "Edit", edit_group_path(@group.id), class: 'main-chat__header__edit__box'
    -# class:"main-chat__header__edit__box"

app/views/messages/_message.html.haml
.message__box{"data-messages-id": "#{message.id}"}
  .message__box__for
    .message__box__for__name
      = message.user.name
    .message__box__for__info
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  .message__box__text
    - if message.body.present?
      %p.message__box__text__view
        = message.body
    = image_tag message.image.url, class: 'massage__box__text__image' if message.image.present?

app/views/messages/index.html.haml
.flash-box
  .wrapper
    .side-chat
      = render "groups/side-chat"
    .main-chat 
      = render "main-chat"
      .message
        = render @messages

      .form
        .form__new_message
          .form__new_message__input-box
            = form_for [@group, @message] do |f|
              = f.text_field :body, class: 'form__new_message__input-box__text', placeholder: 'type a message' 
              = f.label :image, class: 'form__new_message__input-box__text__image' do
                = fa_icon 'image', class: 'far' 
                = f.file_field :image, class: 'form__new_message__input-box__text__image__file' 
              = f.submit 'Send', class: 'form__new_message__sent'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'